#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
  - ../cluster.yml
  tasks:
    - name: Calculate resources
      import_role:
        name: openshift-4-cluster
        tasks_from: calculate-resources.yml
